modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "idler"
version = "${version}"
displayName = "Idler"
authors = "MuriPlz"
description = '''
AFK Management mod, server side
'''
#logoFile = ""

[[dependencies.idler]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.idler]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.idler]]
modId = "luckperms"
mandatory = true
versionRange = "[5.3.0,)"
ordering = "NONE"
side = "SERVER"